stages:
  wrangle:
    cmd: python src/data/wrangle.py
    deps:
      - data/raw/raw.csv
      - src/data/wrangle.py
    outs:
      - data/raw/raw_new.csv

  split_data:
    cmd: python src/data/split_data.py
    deps:
      - data/raw/raw_new.csv
      - src/data/split_data.py
    outs:
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv

  normalize_data:
    cmd: python src/data/normalize_data.py
    deps:
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - src/data/normalize_data.py
    outs:
      - data/processed/X_train_scaled.csv
      - data/processed/X_test_scaled.csv

  grid_search:
    cmd: python src/models/grid_search.py
    deps:
      - data/processed/X_train_scaled.csv
      - data/processed/y_train.csv
      - src/models/grid_search.py
    outs:
      - models/best_params.pkl

  train_model:
    cmd: python src/models/train_model.py
    deps:
      - data/processed/X_train_scaled.csv
      - data/processed/y_train.csv
      - models/best_params.pkl
      - src/models/train_model.py
    outs:
      - models/trained_model.joblib

  evaluate_model:
    cmd: python src/models/evaluate_model.py
    deps:
      - data/processed/X_test_scaled.csv
      - data/processed/y_test.csv
      - models/trained_model.joblib
      - src/models/evaluate_model.py
    outs:
      - data/predictions.csv
    metrics:
      - metrics/scores.json:
          cache: false
